name: CI

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  builds-and-test:
    runs-on: ubuntu-latest

    defaults:  # ВСЕ КОМАНДЫ БУДУТ В backend/
      run:
        working-directory: backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare .env file
        run: cp .env.example .env

      - name: Build up
        run: docker compose build app

      - name: Ruff check
        run: poetry run ruff check .

      - name: Start database
        run: docker compose up -d db

      - name: Run tests
        run: docker compose run --rm app pytest

      - name: Stop containers
        if: always()
        run: docker compose down --volumes