name: Deploy to test


on:
  workflow_dispatch:

jobs:
  deploy-to-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Prepare .env
        run: cp .env.example .env

      - name: Remove previous deploy
        run: docker compose -p redir-test down -v

      - name: Deploy project
        run: APP_PUBLIC_PORT=18001 docker compose -p redir-test up --build -d